# Generated by Django 6.0.2 on 2026-02-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
