# Generated by Django 6.0.2 on 2026-02-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_is_locked_group_age_range_and_more'),
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='max_attendees',
        ),
        migrations.AddField(
            model_name='meet',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meets_attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='meet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meet',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MeetRSVP',
        ),
    ]
