# Generated by Django 6.0.2 on 2026-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
