# Generated by Django 6.0.2 on 2026-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_is_locked_group_age_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='group',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
