# Generated by Django 6.0.2 on 2026-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_location_group_city_group_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mbti',
        ),
    ]
